### ISSUE TITLE
Exam Objectives - Task List

### ISSUE THREAD

**Issue by toddmeinershagen** [toddmeinershagen/70-532#1]
**Create and manage Azure Resource Manager Virtual Machines (30‒35%)**
- [ ] Deploy workloads on Azure Resource Manager (ARM) Virtual Machines (VMs)
  - [x] Identify workloads that can and cannot be deployed
  - [x] Run workloads, including Microsoft and Linux
  - [ ] Create VMs
    - [ ] - via portal
    - [ ] - via powershell
- [ ] Perform configuration management
  - [ ] Automate configuration management by using PowerShell Desired State Configuration and VM Agent (custom script extensions)
  - [ ] Configure VMs using a configuration management tool, such as Puppet or Chef 
  - [ ] Enable remote debugging
- [ ] Configure ARM VM networking
  - [ ] Configure static IP addresses, Network Security Groups (NSG), DNS, User Defined Routes (UDRs), external and internal load balancing with HTTP and TCP health probes, public IPs, firewall rules, and direct server return
  - [ ] design and implement Application Gateway
- [ ] Scale ARM VMs
  - [ ] Scale up and scale down VM sizes, deploy ARM VM Scale Sets (VMSS), configure ARM VMSS auto-scale
- [ ] Design and implement ARM VM storage
  - [ ] Configure disk caching, plan for storage capacity, configure shared storage using Azure File service, configure geo-replication, implement ARM VMs with Standard and Premium Storage
- [ ] Monitor ARM VMs
  - [ ] Configure ARM VM monitoring, configure alerts, configure diagnostic and monitoring storage location
- [ ] Manage ARM VM availability
  - [ ] Configure multiple ARM VMs in an availability set for redundancy, configure each application tier into separate availability sets, combine the Load Balancer with availability sets
